/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useMemo, useState } from 'react';

const STORAGE_KEY = 'serbisyo-toledo-language';
const DEFAULT_LANGUAGE = 'en';

const DICTIONARY = {
  en: {
    language: 'Language',
    home: 'Home',
    about: 'About',
    myDashboard: 'My Dashboard',
    browseServices: 'Browse Services',
    browseShort: 'Browse',
    profile: 'Profile',
    providerProfile: 'Provider Profile',
    providerSettings: 'Provider Settings',
    adminDashboard: 'Admin Dashboard',
    manageUsers: 'Manage Users',
    verifications: 'Verifications',
    reports: 'Reports',
    adminSettings: 'Admin Settings',
    dashboardShort: 'Dashboard',
    usersShort: 'Users',
    verifyShort: 'Verify',
    more: 'More',
    logInShort: 'Log In',
    signUpShort: 'Sign Up',
    authAccessShort: 'Log In / Sign Up',
    openNotifications: 'Open notifications',
    openProfileMenu: 'Open profile menu',
    useLightTheme: 'Use Light Theme',
    useDarkTheme: 'Use Dark Theme',
    schedule: 'Schedule',
    requests: 'Requests',
    myBookings: 'My Bookings',
    notifications: 'Notifications',
    notificationsPageSubtitle: 'Review updates and activity from your bookings and account.',
    notificationsFocusedRequest: 'A related request was highlighted from your recent notification.',
    notificationsLoading: 'Loading notifications...',
    notificationsEmpty: 'No notifications yet',
    notificationsMarkAllRead: 'Mark all read',
    notificationsClearAll: 'Clear all',
    notificationsOpenCenter: 'Open notifications center',
    notificationsJustNow: 'Just now',
    notificationsLoadError: 'Failed to load notifications',
    notificationsMarkAllFailed: 'Failed to mark all notifications as read',
    notificationsClearAllFailed: 'Failed to clear notifications',
    goToRequests: 'Go to Requests',
    editProfile: 'Edit Profile',
    manageProfile: 'Manage Profile',
    editServiceProfile: 'Edit Service Profile',
    postServiceProfile: 'Post Service Profile',
    requestVerification: 'Request Verification',
    verification: 'Verification',
    viewProfileAsClient: 'View Profile as Client',
    viewPublicProfile: 'View Public Profile',
    viewProfilePostFirst: 'View Profile as Client (Post first)',
    settings: 'Settings',
    logOut: 'Log Out',
    logIn: 'Log In',
    signUp: 'Sign Up',
    serviceProvider: 'Service Provider',
    admin: 'Admin',
    client: 'Client',
    footerCopyright: 'All rights reserved.',
    footerTagline: 'Trusted local services for homes and communities in Toledo City.',
    footerQuickLinks: 'Quick Links',
    footerBecomeProvider: 'Become a Provider',
    footerContact: 'Contact',
    footerOfflinePayments: 'Payments are handled offline between client and provider.',
    findServices: 'Find Services',
    searchServiceProviderLocation: 'Search for a service, provider, or location',
    popularSearches: 'Popular searches',
    howItWorksTitle: 'How SerbisyoToledo Works',
    howItWorksSubtitle: 'Choose your role and follow a simple path to start connecting in Toledo City.',
    roleGuideToggle: 'Role guide toggle',
    forClients: 'For Clients',
    forServiceProviders: 'For Service Providers',
    howClientStep1Title: 'Create an Account',
    howClientStep1Description: 'Register as a client using your basic information.',
    howClientStep2Title: 'Find a Service Provider',
    howClientStep2Description: 'Search by service, provider name, rating, or location.',
    howClientStep3Title: 'Send a Booking Request',
    howClientStep3Description: 'Select a provider and submit your preferred schedule and service details.',
    howClientCta: 'Get Started as a Client',
    howProviderStep1Title: 'Register as a Provider',
    howProviderStep1Description: 'Create an account and indicate the service you offer.',
    howProviderStep2Title: 'Complete Your Profile',
    howProviderStep2Description: 'Add your services, experience, location, rate, availability, and portfolio.',
    howProviderStep3Title: 'Receive Service Requests',
    howProviderStep3Description: 'Review incoming booking requests and accept or decline them.',
    howProviderCta: 'Become a Service Provider',
    homeHeroTitle: 'What service do you need?',
    homeHeroSubtitle: 'Find trusted local service providers in Toledo City.',
    homeFeature1Title: 'Skilled Professionals',
    homeFeature1Text: 'Connect with a vast selection of verified and experienced local service providers in Toledo City.',
    homeFeature2Title: 'Build Trust',
    homeFeature2Text: 'View ratings, past accomplished jobs, and profiles to find the right service provider for you.',
    homeFeature3Title: 'Quick Response',
    homeFeature3Text: 'Track your requests and connect with verified service providers fast and easily using the service requests tab.',
    popularServices: 'Popular Services',
    popularServicesSubtitle: 'Choose a category to start browsing providers.',
    browseProvidersForService: 'Browse {service} providers',
    homeCtaTitle: 'Need help today?',
    homeCtaButton: 'Join Serbisyo Toledo',
    feedFetchFailed: 'Failed to fetch service providers',
    feedLoadError: 'We could not load service providers. Please try again.',
    feedChecklistLoadError: 'Unable to load some onboarding progress right now.',
    feedChecklistBasicProfileLabel: 'Complete your basic profile',
    feedChecklistBasicProfileDescription: 'Make sure your name and email are set.',
    feedChecklistOpenSettings: 'Open Settings',
    feedChecklistContactLabel: 'Add your contact information',
    feedChecklistContactDescription: 'Add a phone number so providers can reach you when needed.',
    feedChecklistAddContact: 'Add Contact',
    feedChecklistLocationLabel: 'Add or confirm your location',
    feedChecklistLocationDescription: 'Set your address to help with nearby service matching.',
    feedChecklistUpdateLocation: 'Update Location',
    feedChecklistBrowseLabel: 'Browse available services',
    feedChecklistBrowseDescription: 'Explore providers and service categories.',
    feedChecklistFirstBookingLabel: 'Send your first booking request',
    feedChecklistFirstBookingDescription: 'Open a provider profile and submit a service request.',
    feedChecklistFindProviders: 'Find Providers',
    feedTitle: 'Find a service provider',
    feedSubtitle: 'Compare providers by service, availability, location, and reviews.',
    feedGettingStarted: 'Getting Started',
    feedSearchPlaceholder: 'Search by provider, service, skill, or location',
    feedSearchAria: 'Search by service, provider, or location',
    filters: 'Filters',
    advancedFilters: 'Advanced Filters',
    clearFilters: 'Clear Filters',
    location: 'Location',
    feedEnterLocation: 'Enter location',
    minPrice: 'Min. Price',
    maxPrice: 'Max. Price',
    minimumRating: 'Minimum Rating',
    anyRating: 'Any rating',
    rating45: '4.5+ stars',
    rating4: '4+ stars',
    rating35: '3.5+ stars',
    rating3: '3+ stars',
    feedLoadingProviders: 'Loading service providers...',
    feedNoProvidersTitle: 'No providers match your filters.',
    feedNoProvidersSubtitle: 'Try changing your category, search term, or advanced filters.',
    generalServices: 'General Services',
    startingAt: 'Starting at',
    viewProfile: 'View Profile',
    requestsLoadFailed: 'Failed to load requests',
    requestsServiceCompletedBoth: 'Service has been completed by both parties!',
    requestsCompletionConfirmedWaiting: 'Completion confirmed! Waiting for the other party to confirm.',
    requestsStatusUpdateFailed: 'Failed to update status',
    requestsCancelReasonScheduleConflict: 'Schedule conflict',
    requestsCancellationDetailsRequired: 'Please provide details for cancellation reason.',
    requestsCancelFailed: 'Failed to cancel request',
    requestsRescheduleReasonRequired: 'Reschedule reason is required.',
    cancelServiceRequest: 'Cancel Service Request',
    declineServiceRequest: 'Decline Service Request',
    requestsRescheduleProposalFailed: 'Failed to send reschedule proposal.',
    requestsRescheduleResponseFailed: 'Failed to respond to reschedule proposal',
    requestsDeclineReasonRequired: 'Reason for declining is required.',
    requestsDeclineFailed: 'Failed to decline request',
    requestsDiscussionRequestedSuccess: 'Discussion request sent! The provider will be notified.',
    requestsDiscussionRequestFailed: 'Failed to request discussion',
    requestsDiscussionAcceptedSuccess: 'Discussion accepted! Your phone number has been shared with the client.',
    requestsNoPhoneWarning: 'You have not set a phone number yet.\n\nPlease click your profile icon in the navbar -> Edit Profile, and add your phone number before accepting a discussion request.',
    requestsDiscussionAcceptFailed: 'Failed to accept discussion',
    requestsHideConfirm: 'Remove this request from your view? You can still see it again on another device/browser session.',
    requestsReviewSubmittedSuccess: 'Review submitted successfully! Thank you for your feedback.',
    requestsReviewSubmitFailed: 'Failed to submit review',
    requestsLoading: 'Loading requests...',
    serviceRequests: 'Service Requests',
    myRequests: 'My Bookings',
    requestsProviderSubtitle: 'Manage incoming service requests from clients',
    requestsClientSubtitle: 'Track and manage your bookings',
    all: 'All',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    tryAgain: 'Try Again',
    requestsNoResultsTitle: 'No requests found',
    requestsNoProviderRequestsYet: 'You have not received any service requests yet',
    requestsNoClientRequestsYet: 'You have not made any service requests yet',
    requestsNoFiltered: 'No {filter} requests',
    viewDetails: 'View Details',
    untilDate: 'Until {date}',
    estimatedAmount: 'Est. P{amount}',
    reasonForDeclining: 'Reason for declining',
    reasonForCancellation: 'Reason for cancellation',
    other: 'Other',
    statusPending: 'Pending',
    statusAccepted: 'Accepted',
    statusDeclined: 'Declined',
    statusOnTheWay: 'On the way',
    statusInProgress: 'In progress',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    requestsProviderPhoneLabel: 'Provider\'s Phone:',
    requestsWaitingProviderDiscussion: 'Waiting for provider to accept discussion request...',
    requestsSending: 'Sending...',
    requestsRequestDiscussion: 'Request to Discuss Details',
    requestsPhoneSharedWithClient: 'Phone number shared with client',
    requestsClientWantsDiscuss: 'Client wants to discuss details',
    requestsAccepting: 'Accepting...',
    requestsAcceptAndSharePhone: 'Accept & Share Phone',
    requestsProcessing: 'Processing...',
    requestsAcceptRequest: 'Accept Request',
    requestsDeclineRequest: 'Decline Request',
    requestsImOnMyWay: 'I\'m On My Way',
    requestsMarkServiceComplete: 'Mark Service Complete',
    requestsRemoveFromList: 'Remove from List',
    requestsCancelRequest: 'Cancel Request',
    requestsProposeReschedule: 'Propose Reschedule',
    requestsLeaveReview: 'Leave a Review',
    requestsReviewSubmitted: 'Review submitted',
    requestsCloseCancelDialog: 'Close cancel dialog',
    requestsReasonForCancellationLabel: 'Reason for cancellation',
    requestsCancelReasonNoLongerNeedService: 'No longer need the service',
    requestsCancelReasonProviderUnavailable: 'Provider unavailable',
    requestsCancelReasonClientUnavailable: 'Client unavailable',
    requestsCancelReasonIncorrectBookingInfo: 'Incorrect booking information',
    requestsCancelReasonProviderNoResponse: 'Provider did not respond',
    requestsCancelReasonFoundAnotherProvider: 'Found another provider',
    requestsProvideCancellationDetails: 'Please provide details',
    requestsTellWhyCancelling: 'Tell us why you are cancelling',
    requestsKeepRequest: 'Keep Request',
    requestsCancelling: 'Cancelling...',
    requestsConfirmCancellation: 'Confirm Cancellation',
    requestsCloseRescheduleDialog: 'Close reschedule dialog',
    requestsStartDate: 'Start date',
    requestsEndDate: 'End date',
    requestsStartTime: 'Start time',
    requestsEstimatedDurationMinutes: 'Estimated duration (minutes)',
    requestsExplainProposedSchedule: 'Explain why you are proposing a new schedule',
    requestsCancelAction: 'Cancel',
    requestsSendProposal: 'Send Proposal',
    requestsCloseDeclineDialog: 'Close decline dialog',
    requestsDeclineReasonPlaceholder: 'Explain why you need to decline this request',
    requestsDeclining: 'Declining...',
    requestsConfirmDecline: 'Confirm Decline',
    loginFailedCheckCredentials: 'Login failed. Please check your credentials.',
    loginSubtitle: 'login to your account',
    emailAddress: 'Email Address',
    loginEmailPlaceholder: 'internetgirl@gmail.com',
    password: 'Password',
    togglePasswordVisibility: 'Toggle password visibility',
    forgotPasswordQuestion: 'Forgot Password?',
    loginAs: 'Login as',
    loginClientDesc: 'Looking for service provider',
    loginProviderDesc: 'Offering services to clients',
    loginAdminDesc: 'Manage and oversee services',
    loggingIn: 'Logging in...',
    dontHaveAccount: 'Don\'t have an account?',
    registerHere: 'Register here',
    backToHome: '← Back to home',
    selectValidAccountType: 'Please select a valid account type.',
    registrationSuccessRedirecting: 'Registration successful! A confirmation email was sent to your account. Redirecting...',
    registrationFailedTryAgain: 'Registration failed. Please try again.',
    createYourAccount: 'create your account',
    fullName: 'Full name',
    fullNamePlaceholder: 'Sophia Laforteza',
    createStrongPassword: 'Create a strong password',
    professionalDetails: 'Professional Details',
    profession: 'Profession',
    professionPlaceholder: 'e.g. Electrician, Plumber, Carpenter',
    skillsAndSpecializations: 'Skills & Specializations',
    addSkillPlaceholder: 'Add a skill (e.g. wiring, installation)',
    languagesSpoken: 'Languages Spoken',
    languagesSpokenHelp: 'This helps clients find providers by preferred language.',
    creatingAccount: 'Creating Account...',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    forgotPasswordSuccess: 'If this email is registered, a password reset link has been sent.',
    forgotPasswordFailed: 'Failed to send reset link. Please try again.',
    forgotPasswordSubtitle: 'Forgot password? Enter your email so we can send you a reset link.',
    registeredEmailAddress: 'Registered Email Address',
    registeredEmailPlaceholder: 'you@example.com',
    sendingLink: 'Sending Link...',
    sendResetLink: 'Send Reset Link',
    rememberedPassword: 'Remembered your password?',
    backToLogin: 'Back to Login',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordResetSuccessRedirecting: 'Password reset successful. Redirecting to login...',
    resetPasswordFailed: 'Failed to reset password. Please try again.',
    resetYourPassword: 'reset your password',
    newPassword: 'New Password',
    enterNewPassword: 'Enter new password',
    hide: 'Hide',
    show: 'Show',
    confirmNewPassword: 'Confirm New Password',
    toggleConfirmPasswordVisibility: 'Toggle confirm password visibility',
    updatingPassword: 'Updating Password...',
    resetPassword: 'Reset Password',
    backTo: 'Back to',
    noVerificationToken: 'No verification token provided.',
    verificationFailed: 'Verification failed.',
    loading: 'Loading...',
    verifyingEmail: 'Verifying Your Email...',
    verifyEmailPleaseWait: 'Please wait while we verify your account.',
    emailVerified: 'Email Verified!',
    goToLogin: 'Go to Login',
    verificationFailedTitle: 'Verification Failed',
    backToRegister: 'Back to Register',
    tokenExpired: 'Token Expired',
    noChangesToSave: 'No changes to save.',
    profileSettingsSaved: 'Profile settings saved successfully.',
    failedSaveProfileSettings: 'Failed to save profile settings.',
    changesWereReset: 'Changes were reset.',
    resendVerificationDisabled: 'Resend verification email is temporarily disabled.',
    noEmailForVerification: 'No email address available for verification.',
    verificationEmailSent: 'Verification email sent. Please check your inbox.',
    failedSendVerificationEmail: 'Failed to send verification email.',
    clientSettings: 'Client Settings',
    clientSettingsSubtitle: 'Update your account details and security actions.',
    appearance: 'Appearance',
    account: 'Account',
    contact: 'Contact',
    security: 'Security',
    accountDetails: 'Account Details',
    emailChangesNotSupported: 'Email changes are not supported from settings.',
    bio: 'Bio',
    accountCreatedOn: 'Account created: {date}',
    contactInformation: 'Contact Information',
    phoneNumber: 'Phone Number',
    address: 'Address',
    securityActions: 'Security Actions',
    emailVerificationStatus: 'Email verification status',
    verified: 'Verified',
    notVerified: 'Not verified',
    sending: 'Sending...',
    resendVerificationEmail: 'Resend Verification Email',
    needChangePassword: 'Need to change your password? Use the secure reset flow.',
    openPasswordReset: 'Open Password Reset',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    reset: 'Reset',
    languageOptionCebuano: 'Cebuano',
    languageOptionEnglish: 'English',
    languageOptionFilipino: 'Filipino',
    weekdayMonday: 'Monday',
    weekdayTuesday: 'Tuesday',
    weekdayWednesday: 'Wednesday',
    weekdayThursday: 'Thursday',
    weekdayFriday: 'Friday',
    weekdaySaturday: 'Saturday',
    weekdaySunday: 'Sunday',
    providerSettingsPageTitle: 'Service Provider Settings',
    providerSettingsPageSubtitle: 'Manage your business and account preferences',
    providerSettingsNavBusiness: 'Business',
    providerSettingsNavAvailability: 'Availability',
    providerSettingsNavProfileDetails: 'Profile Details',
    providerSettingsNavPrivacy: 'Privacy',
    providerAccountSettingsTitle: 'Account Settings',
    providerPlaceholderFullName: 'Your full name',
    providerPlaceholderEmail: 'your.email@example.com',
    providerEmailHelpText: 'Your email address is used for login and service notifications',
    providerPersonalPhoneLabel: 'Personal Phone Number',
    providerPlaceholderPhone: '+63 912 345 6789',
    providerPasswordSecurityTitle: 'Password & Security',
    providerChangePassword: 'Change Password',
    providerPasswordSecurityHelp: 'Keep your account secure by using a strong, unique password',
    providerBusinessInformationTitle: 'Business Information',
    providerBusinessNameLabel: 'Business Name',
    providerPlaceholderBusinessName: 'Your business name',
    providerBusinessPhoneLabel: 'Business Phone Number',
    providerBusinessAddressLabel: 'Business Address',
    providerPlaceholderBusinessAddress: '123 Business Street',
    providerBusinessCityLabel: 'Business City',
    providerPlaceholderBusinessCity: 'Toledo',
    providerMinimumJobAmountLabel: 'Minimum Job Amount (P)',
    providerPlaceholderMinimumAmount: '500',
    providerMinimumJobAmountHelp: 'Leave blank for no minimum. Clients can still request, but you can decline.',
    providerServiceAreaLabel: 'Service Area',
    providerServiceAreaToledoCity: 'Toledo City',
    providerServiceAreaToledoPlusBarangays: 'Toledo City + Barangays',
    providerServiceAreaExtended: 'Extended Area (30km)',
    providerServiceAreaProvinceWide: 'Province-wide',
    providerAvailabilityJobSettingsTitle: 'Availability & Job Settings',
    providerSettingsScheduleTitle: 'Schedule & Booking Settings',
    providerSettingsProfileDetailsTitle: 'Profile Details',
    providerAvailabilityStatusLabel: 'Availability Status',
    providerAvailabilityStatusHelp: 'Let clients know if you\'re currently accepting jobs',
    providerAvailabilityStatusAvailable: 'Available',
    providerAvailabilityStatusBusy: 'Busy (Limited)',
    providerAvailabilityStatusUnavailable: 'Unavailable',
    providerShowAvailabilityStatusLabel: 'Show Availability Status',
    providerShowAvailabilityStatusHelp: 'Display your availability on your profile',
    providerAutoAcceptRequestsLabel: 'Auto-Accept Service Requests',
    providerAutoAcceptRequestsHelp: 'Automatically accept requests from verified clients',
    providerBookingConfigurationTitle: 'Booking Configuration',
    providerAllowSameDayBookingLabel: 'Allow same-day booking',
    providerMinAdvanceNoticeLabel: 'Minimum advance notice (minutes)',
    providerMaxAdvanceBookingDaysLabel: 'Maximum advance booking days',
    providerWeeklyAvailabilityBlocksTitle: 'Weekly Availability Blocks',
    providerAddDayBlock: 'Add {day}',
    providerNoWeeklyAvailabilityBlocks: 'No weekly availability blocks yet.',
    providerDayLabel: 'Day',
    requestsEndTime: 'End time',
    providerRemoveBlock: 'Remove Block',
    providerSaveAvailability: 'Save Availability',
    providerDateExceptionsTitle: 'Date Exceptions',
    providerExceptionDateLabel: 'Exception date',
    providerExceptionTypeLabel: 'Exception type',
    providerExceptionTypeAvailableOverride: 'Available override',
    providerExceptionTypeUnavailable: 'Unavailable',
    providerExceptionTypeBooked: 'Booked',
    providerExceptionTypeVacation: 'Vacation',
    providerExceptionStartTimeOptional: 'Start time (optional)',
    providerExceptionEndTimeOptional: 'End time (optional)',
    providerExceptionReasonOptional: 'Reason (optional)',
    providerAddException: 'Add Exception',
    providerNoDateExceptionsConfigured: 'No date exceptions configured.',
    providerWholeDay: 'Whole day',
    providerRemoveException: 'Remove',
    providerSaveLanguages: 'Save Languages',
    providerCredentialsCertificatesTitle: 'Credentials and Certificates',
    providerCredentialNameLabel: 'Credential name',
    providerCredentialTypeLabel: 'Credential type',
    providerIssuingOrganizationLabel: 'Issuing organization',
    providerCredentialIdLabel: 'Credential ID',
    providerIssueDateLabel: 'Issue date',
    providerExpirationDateLabel: 'Expiration date',
    providerCredentialDoesNotExpire: 'This credential does not expire',
    providerCredentialUrlLabel: 'Credential URL',
    providerCredentialDocumentLabel: 'Document (PDF/JPG/PNG)',
    providerAddCredential: 'Add Credential',
    providerSavedCredentialsTitle: 'Saved Credentials',
    providerLoadingCredentials: 'Loading credentials...',
    providerNoCredentialsYet: 'No credentials yet.',
    providerPendingReview: 'Pending Review',
    providerSubmitForReview: 'Submit for Review',
    providerNotificationSettingsTitle: 'Notification Settings',
    providerPushNotificationsLabel: 'Push Notifications',
    providerPushNotificationsHelp: 'Receive browser notifications for new service requests',
    providerEmailAlertsLabel: 'Email Alerts',
    providerEmailAlertsHelp: 'Get notified about new requests and messages via email',
    providerSmsNotificationsLabel: 'SMS Notifications',
    providerSmsNotificationsHelp: 'Get urgent alerts via SMS (may incur charges)',
    providerPrivacySettingsTitle: 'Privacy Settings',
    providerProfileVisibilityLabel: 'Profile Visibility',
    providerProfileVisibilityHelp: 'Who can see your profile and services',
    providerVisibilityPublic: 'Public',
    providerVisibilityPrivate: 'Private (By Appointment)',
    providerVisibilityVerifiedOnly: 'Verified Clients Only',
    providerAllowDirectMessagesLabel: 'Allow Direct Messages',
    providerAllowDirectMessagesHelp: 'Allow clients to send you direct messages',
    providerSettingsSavedSuccess: 'Settings saved successfully!',
    providerSettingsSaveFailed: 'Failed to save settings',
    providerAvailabilityUpdatedSuccess: 'Availability updated successfully.',
    providerAvailabilitySaveFailed: 'Failed to save availability settings',
    providerLanguagesUpdatedSuccess: 'Languages updated successfully.',
    providerLanguagesUpdateFailed: 'Failed to update languages',
    providerExceptionDateRequired: 'Please choose an exception date.',
    providerExceptionTimePairRequired: 'Provide both start and end time, or leave both blank for whole-day exception.',
    providerAddExceptionFailed: 'Failed to add availability exception',
    providerDeleteExceptionFailed: 'Failed to delete exception',
    providerCredentialNameTypeRequired: 'Credential name and type are required.',
    providerCredentialSavedSuccess: 'Credential saved successfully. Submit it for review when ready.',
    providerCredentialCreateFailed: 'Failed to create credential',
    providerCredentialSubmittedSuccess: 'Credential submitted for review.',
    providerCredentialSubmitFailed: 'Failed to submit credential',
    adminReportsLoadError: 'We could not load reports. Please try again.',
    adminReportsResolutionNotesRequiredPrompt: 'Resolution notes (required):',
    adminReportsResolutionNotesRequiredAlert: 'Resolution notes are required for this action.',
    adminReportsResolutionNotesRequiredMessage: 'Resolution notes are required.',
    adminReportsOptionalModerationNotesPrompt: 'Optional moderation notes:',
    adminReportsUpdateFailed: 'Failed to update report',
    adminReportsDecisionNoteRequired: 'Admin note is required before submitting a decision.',
    adminReportsSubmitDecisionFailed: 'Failed to submit decision',
    adminReportsSubtitle: 'Review reported activity and decide what action should be taken.',
    adminUnderReview: 'Under Review',
    adminProcessed: 'Processed',
    adminSearchReportsPlaceholder: 'Search reports...',
    adminFilterReportsByStatus: 'Filter reports by status',
    adminDismissed: 'Dismissed',
    adminResolved: 'Resolved',
    adminActionTaken: 'Action taken',
    adminEvidenceImage: 'Evidence image',
    adminViewAttachedEvidenceImage: 'View attached evidence image',
    adminResolution: 'Resolution',
    adminWorking: 'Working...',
    adminReviewReport: 'Review Report',
    adminMakeDecision: 'Make Decision',
    adminHideDetails: 'Hide Details',
    adminEvidenceImagePreview: 'Evidence image preview',
    adminCloseImagePreview: 'Close image preview',
    adminNoReportsRequiringAttention: 'No reports requiring attention.',
    adminTryAdjustingSearchFilter: 'Try adjusting your search or filter criteria.',
    adminCloseDecisionDialog: 'Close decision dialog',
    adminDecision: 'Decision',
    adminDecisionDismiss: 'No violation - Dismiss',
    adminDecisionWarn: 'Minor violation - Warn',
    adminDecisionSuspend: 'Serious or repeated violation - Suspend',
    adminDecisionBan: 'Severe violation - Ban',
    adminNote: 'Admin note',
    adminDecisionReasonPlaceholder: 'Explain the reason for this decision',
    adminSubmitting: 'Submitting...',
    adminSubmitDecision: 'Submit Decision',
    adminOperationalDataRefreshed: 'Operational data refreshed.',
    adminOperationalDataPartialError: 'Some operational data could not be loaded. Review API health and retry refresh.',
    adminOperationalSnapshotExported: 'Operational snapshot exported.',
    adminSettingsSubtitle: 'Live operations, moderation status, and admin control shortcuts.',
    adminOverview: 'Overview',
    adminModeration: 'Moderation',
    adminSecurityHealth: 'Security and Health',
    adminPlatformOperationsOverview: 'Platform Operations Overview',
    adminRefreshing: 'Refreshing...',
    adminRefreshMetrics: 'Refresh Metrics',
    adminExportSnapshotJson: 'Export Snapshot JSON',
    adminLiveTotals: 'Live Totals',
    adminSuspendedUsers: 'Suspended users',
    adminUnverifiedProviders: 'Unverified providers',
    adminModerationQueues: 'Moderation Queues',
    adminVerificationRequestsPending: 'Verification requests pending',
    adminRejectedVerificationRequests: 'Rejected verification requests',
    adminReportsPending: 'Reports pending',
    adminReportsUnderReview: 'Reports under review',
    adminModerationActions: 'Moderation Actions',
    adminModerationActionsHelp: 'Open dedicated admin pages to process requests and enforce account actions.',
    adminOpenVerificationQueue: 'Open Verification Queue',
    adminOpenReportsQueue: 'Open Reports Queue',
    adminOpenUserManagement: 'Open User Management',
    adminSecurityHealthStatus: 'Security and Health Status',
    adminApiHealth: 'API Health',
    adminTimestamp: 'Timestamp',
    adminNotAvailable: 'Not available',
    adminEndpoint: 'Endpoint',
    adminDatabase: 'Database',
    adminOperationalNotes: 'Operational Notes',
    adminOperationalNotesLine1: 'Admin Settings is intentionally read-focused in this release to avoid fake system toggles.',
    adminOperationalNotesLine2: 'Use dedicated moderation screens for user suspension, provider verification review, and report handling.',
    adminUserDetailsOverview: 'User Details Overview',
    adminType: 'Type',
    adminNotAvailableShort: 'N/A',
    adminYes: 'Yes',
    adminNo: 'No',
    adminUserActivitySummary: 'User Activity Summary',
    adminTotalRequests: 'Total Requests',
    adminCompletedRequests: 'Completed Requests',
    adminActiveRequests: 'Active Requests',
    adminReportsSubmitted: 'Reports Submitted',
    adminReportsReceived: 'Reports Received',
    adminLastRequestActivity: 'Last Request Activity',
    adminLastReportActivity: 'Last Report Activity',
    adminUsersListMobileAria: 'Users list for mobile',
    adminVerification: 'Verification',
    adminJoinDate: 'Join Date',
    adminUser: 'User',
    adminActions: 'Actions',
    adminCloseDialog: 'Close dialog',
    adminOkay: 'Okay',
    adminRejectionReason: 'Rejection Reason',
    adminPreviewGovernmentIdDocument: 'Preview government ID document',
    adminViewGovernmentId: 'View Government ID',
    adminPreviewCertificationsDocument: 'Preview certifications document',
    adminViewCertifications: 'View Certifications',
    adminNoDocumentSubmitted: 'No document submitted',
    adminApproving: 'Approving...',
    adminApproveVerification: 'Approve Verification',
    adminRejectVerification: 'Reject Verification',
    adminPreviewVerificationDocument: 'Preview verification document',
    adminProviderCredentialReviews: 'Provider Credential Reviews',
    adminReviewSubmittedCredentials: 'Review submitted credentials from service providers',
    adminExpired: 'Expired',
    adminUnverified: 'Unverified',
    adminLoadingProviderCredentials: 'Loading provider credentials...',
    adminUnknownProvider: 'Unknown Provider',
    adminCredentialLabel: 'Credential',
    adminCredentialField: 'Credential',
    adminUnnamedCredential: 'Unnamed credential',
    adminIssuerField: 'Issuer',
    adminNotProvided: 'Not provided',
    adminReviewNote: 'Review Note',
    adminPreviewCredentialDocument: 'Preview credential document',
    adminViewCredentialDocument: 'View Credential Document',
    adminApproveCredential: 'Approve Credential',
    adminRejectCredential: 'Reject Credential',
    adminExpiring: 'Expiring...',
    adminMarkExpired: 'Mark Expired',
    adminNoProviderCredentialsFound: 'No provider credentials found',
    adminCloseDocumentPreview: 'Close document preview',
    adminResetImageZoom: 'Reset image zoom',
    adminEnlargeImage: 'Enlarge image',
    adminResetZoom: 'Reset Zoom',
    adminEnlarge: 'Enlarge',
    adminPdfPreviewFallback: 'If the PDF cannot be previewed in this browser, download support may be required in your environment.',
    adminPreviewUnavailableForType: 'Preview is not available for this document type.',
    adminRejectVerificationRequest: 'Reject Verification Request',
    adminCloseRejectionDialog: 'Close rejection dialog',
    adminConfirmRejection: 'Confirm Rejection',
    adminCloseCredentialRejectionDialog: 'Close credential rejection dialog',
    pendingVerifications: 'Pending Verifications',
    activeReports: 'Active Reports',
    verifiedProviders: 'Verified Providers',
    totalUsers: 'Total Users',
    verificationRequests: 'Verification Requests',
    userReports: 'User Reports',
    loadingVerificationRequests: 'Loading verification requests...',
    noVerificationRequestsFound: 'No verification requests found',
    noVerificationRequestsInDatabase: 'There are currently no verification requests in the database.',
    emailLabel: 'Email',
    submittedLabel: 'Submitted',
    statusLabel: 'Status',
    phoneLabel: 'Phone',
    reviewRequest: 'Review Request',
    loadingReports: 'Loading reports...',
    noReportsFound: 'No reports found',
    noReportsInDatabase: 'There are currently no user reports in the database.',
    reportedBy: 'Reported by',
    reason: 'Reason',
    date: 'Date',
    viewReport: 'View Report',
    viewAllVerifications: 'View All Verifications ->',
    viewAllReports: 'View All Reports ->',
    failedLoadUsers: 'Failed to load users',
    unableLoadDetails: 'Unable to Load Details',
    failedFetchUserDetails: 'Failed to fetch user details',
    updateFailed: 'Update Failed',
    failedUpdateUserStatus: 'Failed to update user status',
    failedUpdateVerificationStatus: 'Failed to update verification status',
    unableLoadActivity: 'Unable to Load Activity',
    failedFetchUserActivity: 'Failed to fetch user activity',
    userManagement: 'User Management',
    userManagementSubtitle: 'Review account status, verification, and user activity.',
    searchUsersPlaceholder: 'Search users...',
    filterUsersByRole: 'Filter users by role',
    allTypes: 'All Types',
    clients: 'Clients',
    serviceProviders: 'Service Providers',
    admins: 'Admins',
    filterUsersByStatus: 'Filter users by account status',
    allStatuses: 'All Statuses',
    pending: 'Pending',
    suspended: 'Suspended',
    updating: 'Updating...',
    deactivate: 'Deactivate',
    reactivate: 'Reactivate',
    unverifyProvider: 'Unverify Provider',
    verifyProvider: 'Verify Provider',
    viewActivity: 'View Activity',
    loadingUsers: 'Loading users...',
    failedLoadVerificationRequests: 'Failed to load verification requests',
    failedLoadProviderCredentials: 'Failed to load provider credentials',
    rejectionReasonRequired: 'Rejection reason is required.',
    failedRejectRequest: 'Failed to reject request',
    failedReviewRequest: 'Failed to review request',
    failedRejectCredential: 'Failed to reject credential',
    failedReviewCredential: 'Failed to review credential',
    verificationRequestsSubtitle: 'Review and manage service provider verification requests',
    approved: 'Approved',
    rejected: 'Rejected',
    searchVerificationPlaceholder: 'Search by name, email, or profession...',
  },
  ceb: {
    language: 'Pinulongan',
    home: 'Balay',
    about: 'Mahitungod',
    myDashboard: 'Akong Dashboard',
    browseServices: 'Tan-awa ang mga Serbisyo',
    browseShort: 'Tan-awa',
    profile: 'Profile',
    providerProfile: 'Profile sa Provider',
    providerSettings: 'Settings sa Provider',
    adminDashboard: 'Admin Dashboard',
    manageUsers: 'Pagdumala sa Users',
    verifications: 'Mga Verification',
    reports: 'Mga Report',
    adminSettings: 'Admin Settings',
    dashboardShort: 'Dashboard',
    usersShort: 'Users',
    verifyShort: 'Verify',
    more: 'Uban pa',
    logInShort: 'Login',
    signUpShort: 'Sign Up',
    authAccessShort: 'Login / Sign Up',
    openNotifications: 'Ablihi ang notifications',
    openProfileMenu: 'Ablihi ang profile menu',
    useLightTheme: 'Gamita ang Light Theme',
    useDarkTheme: 'Gamita ang Dark Theme',
    schedule: 'Eskedyul',
    requests: 'Mga Hangyo',
    myBookings: 'Akong Bookings',
    notifications: 'Mga Notification',
    notificationsPageSubtitle: 'Tan-awa ang mga update ug kalihokan sa imong booking ug account.',
    notificationsFocusedRequest: 'Gi-highlight ang may kalabutan nga request gikan sa pinakabag-ong notification.',
    notificationsLoading: 'Nag-load sa notifications...',
    notificationsEmpty: 'Wala pay notifications',
    notificationsMarkAllRead: 'Markahi tanan nga nabasa',
    notificationsClearAll: 'I-clear tanan',
    notificationsOpenCenter: 'Ablihi ang notification center',
    notificationsJustNow: 'Karon lang',
    notificationsLoadError: 'Napakyas ang pag-load sa notifications',
    notificationsMarkAllFailed: 'Napakyas ang pagmarka sa tanan nga nabasa',
    notificationsClearAllFailed: 'Napakyas ang pag-clear sa notifications',
    goToRequests: 'Adto sa Mga Hangyo',
    editProfile: 'Usba ang Profile',
    manageProfile: 'Dumalahon ang Profile',
    editServiceProfile: 'Usba ang Service Profile',
    postServiceProfile: 'I-post ang Service Profile',
    requestVerification: 'Mangayo og Verification',
    verification: 'Verification',
    viewProfileAsClient: 'Tan-awa ang Profile isip Kliyente',
    viewPublicProfile: 'Tan-awa ang Public Profile',
    viewProfilePostFirst: 'Tan-awa ang Profile isip Kliyente (Pag-post una)',
    settings: 'Mga Setting',
    logOut: 'Pag-logout',
    logIn: 'Pag-login',
    signUp: 'Pag-sign up',
    serviceProvider: 'Service Provider',
    admin: 'Admin',
    client: 'Kliyente',
    footerCopyright: 'Tanang katungod gitagana.',
    footerTagline: 'Kasaligang lokal nga serbisyo para sa panimalay ug komunidad sa Toledo City.',
    footerQuickLinks: 'Mga Dali nga Link',
    footerBecomeProvider: 'Mahimong Service Provider',
    footerContact: 'Kontak',
    footerOfflinePayments: 'Ang bayad himuon offline tali sa kliyente ug provider.',
    findServices: 'Pangitaa ang Serbisyo',
    searchServiceProviderLocation: 'Pangitaa ang serbisyo, provider, o lokasyon',
    popularSearches: 'Popular nga pagpangita',
    howItWorksTitle: 'Giunsa Pagtrabaho ang SerbisyoToledo',
    howItWorksSubtitle: 'Pilia ang imong role ug sundan ang yano nga paagi sa pagkonektar sa Toledo City.',
    roleGuideToggle: 'Role guide toggle',
    forClients: 'Para sa mga Kliyente',
    forServiceProviders: 'Para sa mga Service Provider',
    howClientStep1Title: 'Paghimo og Account',
    howClientStep1Description: 'Pagparehistro isip kliyente gamit ang imong batakang impormasyon.',
    howClientStep2Title: 'Pangita og Service Provider',
    howClientStep2Description: 'Pangita pinaagi sa serbisyo, ngalan sa provider, rating, o lokasyon.',
    howClientStep3Title: 'Ipadala ang Booking Request',
    howClientStep3Description: 'Pilia ang provider ug isumite ang gusto nimong schedule ug detalye sa serbisyo.',
    howClientCta: 'Sugdi isip Kliyente',
    howProviderStep1Title: 'Pagparehistro isip Provider',
    howProviderStep1Description: 'Paghimo og account ug isulti ang serbisyong imong gihatag.',
    howProviderStep2Title: 'Kompletoha ang Imong Profile',
    howProviderStep2Description: 'Idugang ang serbisyo, kasinatian, lokasyon, presyo, availability, ug portfolio.',
    howProviderStep3Title: 'Dawata ang Service Requests',
    howProviderStep3Description: 'Susiha ang mosulod nga booking requests ug dawata o balibari kini.',
    howProviderCta: 'Mahimong Service Provider',
    homeHeroTitle: 'Unsa nga serbisyo ang imong kinahanglan?',
    homeHeroSubtitle: 'Pangitaa ang kasaligan nga lokal nga service provider sa Toledo City.',
    homeFeature1Title: 'Han-asan nga mga Propesyonal',
    homeFeature1Text: 'Konektahi ang daghang napamatud-an ug eksperyensiyadong lokal nga service providers sa Toledo City.',
    homeFeature2Title: 'Pagtukod og Pagsalig',
    homeFeature2Text: 'Tan-awa ang ratings, natapos nga trabaho, ug mga profile aron makapili sa hustong provider para nimo.',
    homeFeature3Title: 'Paspas nga Tubag',
    homeFeature3Text: 'Subaya ang imong requests ug dali nga makonektar sa verified nga service providers gamit ang service requests tab.',
    popularServices: 'Popular nga mga Serbisyo',
    popularServicesSubtitle: 'Pilia ang kategorya aron magsugod sa pagtan-aw sa providers.',
    browseProvidersForService: 'Tan-awa ang mga provider sa {service}',
    homeCtaTitle: 'Nanginahanglan kag tabang karon?',
    homeCtaButton: 'Apil sa Serbisyo Toledo',
    feedFetchFailed: 'Napakyas ang pagkuha sa service providers',
    feedLoadError: 'Dili ma-load ang service providers. Palihog sulayi pag-usab.',
    feedChecklistLoadError: 'Dili ma-load ang uban onboarding progress karon.',
    feedChecklistBasicProfileLabel: 'Kompletoha ang batakang profile',
    feedChecklistBasicProfileDescription: 'Siguroa nga sakto ang imong ngalan ug email.',
    feedChecklistOpenSettings: 'Ablihi ang Settings',
    feedChecklistContactLabel: 'Idugang ang contact information',
    feedChecklistContactDescription: 'Idugang ang phone number aron matawagan ka sa providers kon kinahanglan.',
    feedChecklistAddContact: 'Idugang Contact',
    feedChecklistLocationLabel: 'Idugang o kumpirmaha ang imong lokasyon',
    feedChecklistLocationDescription: 'I-set ang imong address aron mas sayon ang pagmatch sa duol nga serbisyo.',
    feedChecklistUpdateLocation: 'Usba Lokasyon',
    feedChecklistBrowseLabel: 'Tan-awa ang available nga serbisyo',
    feedChecklistBrowseDescription: 'Susiha ang providers ug service categories.',
    feedChecklistFirstBookingLabel: 'Ipadala ang una nimong booking request',
    feedChecklistFirstBookingDescription: 'Ablihi ang provider profile ug isumite ang service request.',
    feedChecklistFindProviders: 'Pangita Providers',
    feedTitle: 'Pangita og service provider',
    feedSubtitle: 'Ikumpara ang providers pinaagi sa serbisyo, availability, lokasyon, ug reviews.',
    feedGettingStarted: 'Pagsugod',
    feedSearchPlaceholder: 'Pangita pinaagi sa provider, serbisyo, skill, o lokasyon',
    feedSearchAria: 'Pangita pinaagi sa serbisyo, provider, o lokasyon',
    filters: 'Filters',
    advancedFilters: 'Advanced Filters',
    clearFilters: 'I-clear ang Filters',
    location: 'Lokasyon',
    feedEnterLocation: 'Isulod ang lokasyon',
    minPrice: 'Min. Presyo',
    maxPrice: 'Max. Presyo',
    minimumRating: 'Minimum Rating',
    anyRating: 'Bisan unsang rating',
    rating45: '4.5+ bituon',
    rating4: '4+ bituon',
    rating35: '3.5+ bituon',
    rating3: '3+ bituon',
    feedLoadingProviders: 'Nag-load sa service providers...',
    feedNoProvidersTitle: 'Walay provider nga mohaom sa imong filters.',
    feedNoProvidersSubtitle: 'Sulayi usba ang category, search term, o advanced filters.',
    generalServices: 'General nga Serbisyo',
    startingAt: 'Sugod sa',
    viewProfile: 'Tan-awa ang Profile',
    requestsLoadFailed: 'Napakyas ang pag-load sa requests',
    requestsServiceCompletedBoth: 'Nahuman na ang serbisyo sa duha ka partido!',
    requestsCompletionConfirmedWaiting: 'Nakumpirma ang completion! Naghulat pa sa pikas partido nga mokumpirma.',
    requestsStatusUpdateFailed: 'Napakyas ang pag-update sa status',
    requestsCancelReasonScheduleConflict: 'Schedule conflict',
    requestsCancellationDetailsRequired: 'Palihog hatagi og detalye ang rason sa cancellation.',
    requestsCancelFailed: 'Napakyas ang pagkansela sa request',
    requestsRescheduleReasonRequired: 'Kinahanglan ang rason sa reschedule.',
    cancelServiceRequest: 'Kanselahon ang Service Request',
    declineServiceRequest: 'I-decline ang Service Request',
    requestsRescheduleProposalFailed: 'Napakyas ang pagpadala sa reschedule proposal.',
    requestsRescheduleResponseFailed: 'Napakyas ang pagtubag sa reschedule proposal',
    requestsDeclineReasonRequired: 'Kinahanglan ang rason sa pag-decline.',
    requestsDeclineFailed: 'Napakyas ang pag-decline sa request',
    requestsDiscussionRequestedSuccess: 'Napadala na ang discussion request! Ma-notify ang provider.',
    requestsDiscussionRequestFailed: 'Napakyas ang discussion request',
    requestsDiscussionAcceptedSuccess: 'Gidawat ang discussion! Na-share na ang imong phone number sa kliyente.',
    requestsNoPhoneWarning: 'Wala pa kay na-set nga phone number.\n\nPalihog i-click ang imong profile icon sa navbar -> Edit Profile, ug idugang ang imong phone number sa dili pa modawat og discussion request.',
    requestsDiscussionAcceptFailed: 'Napakyas ang pagdawat sa discussion',
    requestsHideConfirm: 'Tangtangon ba nimo kini nga request sa imong view? Makita gihapon nimo kini sa laing device/browser session.',
    requestsReviewSubmittedSuccess: 'Naisumite na ang review! Salamat sa imong feedback.',
    requestsReviewSubmitFailed: 'Napakyas ang pagsumite sa review',
    requestsLoading: 'Nag-load sa requests...',
    serviceRequests: 'Service Requests',
    myRequests: 'Akong Bookings',
    requestsProviderSubtitle: 'Dumalahon ang incoming service requests gikan sa mga kliyente',
    requestsClientSubtitle: 'Subaya ug dumalahon ang imong bookings',
    all: 'Tanan',
    active: 'Aktibo',
    completed: 'Nahuman',
    cancelled: 'Nakansela',
    tryAgain: 'Sulayi Pag-usab',
    requestsNoResultsTitle: 'Walay request nga nakita',
    requestsNoProviderRequestsYet: 'Wala pa kay nadawat nga service requests',
    requestsNoClientRequestsYet: 'Wala pa kay nahimong service requests',
    requestsNoFiltered: 'Walay {filter} nga requests',
    viewDetails: 'Tan-awa ang Detalye',
    untilDate: 'Kutob sa {date}',
    estimatedAmount: 'Tantiya P{amount}',
    reasonForDeclining: 'Rason sa pag-decline',
    reasonForCancellation: 'Rason sa cancellation',
    other: 'Uban pa',
    statusPending: 'Pending',
    statusAccepted: 'Gidawat',
    statusDeclined: 'Gi-decline',
    statusOnTheWay: 'Padulong na',
    statusInProgress: 'Nagpadayon',
    statusCompleted: 'Nahuman',
    statusCancelled: 'Nakansela',
    requestsProviderPhoneLabel: 'Telepono sa Provider:',
    requestsWaitingProviderDiscussion: 'Naghulat nga dawaton sa provider ang discussion request...',
    requestsSending: 'Nagpadala...',
    requestsRequestDiscussion: 'Mangayo og Discussion sa Detalye',
    requestsPhoneSharedWithClient: 'Na-share na ang numero sa telepono sa kliyente',
    requestsClientWantsDiscuss: 'Ang kliyente gustong maghisgot sa detalye',
    requestsAccepting: 'Ginadawat...',
    requestsAcceptAndSharePhone: 'Dawata ug I-share ang Telepono',
    requestsProcessing: 'Gina-proseso...',
    requestsAcceptRequest: 'Dawata ang Request',
    requestsDeclineRequest: 'I-decline ang Request',
    requestsImOnMyWay: 'Padulong Na Ko',
    requestsMarkServiceComplete: 'Markahi nga Nahuman ang Serbisyo',
    requestsRemoveFromList: 'Tangtanga sa Listahan',
    requestsCancelRequest: 'Kanselahon ang Request',
    requestsProposeReschedule: 'Mosugyot og Reschedule',
    requestsLeaveReview: 'Biya-i og Review',
    requestsReviewSubmitted: 'Naisumite na ang review',
    requestsCloseCancelDialog: 'Sirad-i ang cancel dialog',
    requestsReasonForCancellationLabel: 'Rason sa cancellation',
    requestsCancelReasonNoLongerNeedService: 'Dili na kinahanglan ang serbisyo',
    requestsCancelReasonProviderUnavailable: 'Dili available ang provider',
    requestsCancelReasonClientUnavailable: 'Dili available ang kliyente',
    requestsCancelReasonIncorrectBookingInfo: 'Sayop ang booking information',
    requestsCancelReasonProviderNoResponse: 'Wala mitubag ang provider',
    requestsCancelReasonFoundAnotherProvider: 'Nakakita og lain nga provider',
    requestsProvideCancellationDetails: 'Palihog ihatag ang detalye',
    requestsTellWhyCancelling: 'Isulti nganong imong kanselahon',
    requestsKeepRequest: 'Padayona ang Request',
    requestsCancelling: 'Ginakansela...',
    requestsConfirmCancellation: 'Kumpirmahi ang Cancellation',
    requestsCloseRescheduleDialog: 'Sirad-i ang reschedule dialog',
    requestsStartDate: 'Sugod nga petsa',
    requestsEndDate: 'Katapusan nga petsa',
    requestsStartTime: 'Oras sa pagsugod',
    requestsEstimatedDurationMinutes: 'Tantiya nga gidugayon (minuto)',
    requestsExplainProposedSchedule: 'Isaysay nganong nagsugyot ka og bag-ong iskedyul',
    requestsCancelAction: 'Kansela',
    requestsSendProposal: 'Ipadala ang Proposal',
    requestsCloseDeclineDialog: 'Sirad-i ang decline dialog',
    requestsDeclineReasonPlaceholder: 'Isaysay nganong kinahanglan nimo i-decline kini nga request',
    requestsDeclining: 'Gina-decline...',
    requestsConfirmDecline: 'Kumpirmahi ang Pag-decline',
    loginFailedCheckCredentials: 'Napakyas ang pag-login. Palihog susiha ang imong credentials.',
    loginSubtitle: 'pag-login sa imong account',
    emailAddress: 'Email Address',
    loginEmailPlaceholder: 'internetgirl@gmail.com',
    password: 'Password',
    togglePasswordVisibility: 'I-toggle ang pagpakita sa password',
    forgotPasswordQuestion: 'Nakalimot sa Password?',
    loginAs: 'Login isip',
    loginClientDesc: 'Nangita og service provider',
    loginProviderDesc: 'Naghatag og serbisyo sa mga kliyente',
    loginAdminDesc: 'Pagdumala ug pagbantay sa serbisyo',
    loggingIn: 'Nag-login...',
    dontHaveAccount: 'Wala kay account?',
    registerHere: 'Pag-register diri',
    backToHome: '← Balik sa home',
    selectValidAccountType: 'Palihog pili og valid nga account type.',
    registrationSuccessRedirecting: 'Nakalampuson ang registration! Adunay confirmation email nga gipadala. I-redirect ka karon...',
    registrationFailedTryAgain: 'Napakyas ang registration. Palihog sulayi pag-usab.',
    createYourAccount: 'paghimo sa imong account',
    fullName: 'Tibuok ngalan',
    fullNamePlaceholder: 'Sophia Laforteza',
    createStrongPassword: 'Paghimo og lig-on nga password',
    professionalDetails: 'Propesyonal nga Detalye',
    profession: 'Propesyon',
    professionPlaceholder: 'pananglitan: Electrician, Plumber, Carpenter',
    skillsAndSpecializations: 'Mga Kahanas ug Espesyalisasyon',
    addSkillPlaceholder: 'Idugang ang kahanas (pananglitan: wiring, installation)',
    languagesSpoken: 'Sinultian nga Nahibal-an',
    languagesSpokenHelp: 'Makatabang kini sa mga kliyente sa pagpangita base sa preferred nga pinulongan.',
    creatingAccount: 'Naghimo og Account...',
    createAccount: 'Paghimo og Account',
    alreadyHaveAccount: 'Aduna na kay account?',
    loginHere: 'Login diri',
    forgotPasswordSuccess: 'Kung rehistrado kini nga email, napadala na ang reset link.',
    forgotPasswordFailed: 'Napakyas ang pagpadala sa reset link. Palihog sulayi pag-usab.',
    forgotPasswordSubtitle: 'Nakalimot sa password? Isulod ang imong email aron mapadal-an ka og reset link.',
    registeredEmailAddress: 'Rehistradong Email Address',
    registeredEmailPlaceholder: 'you@example.com',
    sendingLink: 'Nagpadala og Link...',
    sendResetLink: 'Ipadala ang Reset Link',
    rememberedPassword: 'Nahinumduman nimo ang password?',
    backToLogin: 'Balik sa Login',
    passwordsDoNotMatch: 'Dili pareho ang mga password.',
    passwordResetSuccessRedirecting: 'Nakalampuson ang pag-reset sa password. I-redirect sa login...',
    resetPasswordFailed: 'Napakyas ang pag-reset sa password. Palihog sulayi pag-usab.',
    resetYourPassword: 'i-reset ang imong password',
    newPassword: 'Bag-ong Password',
    enterNewPassword: 'Isulod ang bag-ong password',
    hide: 'Itago',
    show: 'Ipakita',
    confirmNewPassword: 'Kumpirmahi ang Bag-ong Password',
    toggleConfirmPasswordVisibility: 'I-toggle ang pagpakita sa confirm password',
    updatingPassword: 'Nag-update sa Password...',
    resetPassword: 'I-reset ang Password',
    backTo: 'Balik sa',
    noVerificationToken: 'Walay verification token nga gihatag.',
    verificationFailed: 'Napakyas ang verification.',
    loading: 'Nag-load...',
    verifyingEmail: 'Gina-verify ang Imong Email...',
    verifyEmailPleaseWait: 'Palihog hulata samtang gi-verify ang imong account.',
    emailVerified: 'Na-verify ang Email!',
    goToLogin: 'Adto sa Login',
    verificationFailedTitle: 'Napakyas ang Verification',
    backToRegister: 'Balik sa Register',
    tokenExpired: 'Napaso ang Token',
    noChangesToSave: 'Walay kausaban nga i-save.',
    profileSettingsSaved: 'Nakaluwas ang profile settings.',
    failedSaveProfileSettings: 'Napakyas ang pag-save sa profile settings.',
    changesWereReset: 'Na-reset ang mga kausaban.',
    resendVerificationDisabled: 'Temporarily disabled ang resend verification email.',
    noEmailForVerification: 'Walay email address para sa verification.',
    verificationEmailSent: 'Napadala na ang verification email. Palihog tan-awa ang imong inbox.',
    failedSendVerificationEmail: 'Napakyas ang pagpadala sa verification email.',
    clientSettings: 'Client Settings',
    clientSettingsSubtitle: 'Usba ang detalye sa account ug security actions.',
    appearance: 'Panagway',
    account: 'Account',
    contact: 'Contact',
    security: 'Security',
    accountDetails: 'Detalye sa Account',
    emailChangesNotSupported: 'Dili suportado ang pag-usab sa email gikan sa settings.',
    bio: 'Bio',
    accountCreatedOn: 'Gihimo ang account: {date}',
    contactInformation: 'Contact Information',
    phoneNumber: 'Numero sa Telepono',
    address: 'Address',
    securityActions: 'Mga Security Action',
    emailVerificationStatus: 'Status sa email verification',
    verified: 'Verified',
    notVerified: 'Wala na-verify',
    sending: 'Nagpadala...',
    resendVerificationEmail: 'I-resend ang Verification Email',
    needChangePassword: 'Nanginahanglan ba ka og pag-usab sa password? Gamita ang secure reset flow.',
    openPasswordReset: 'Ablihi ang Password Reset',
    saving: 'Nag-save...',
    saveChanges: 'I-save ang mga Kausaban',
    reset: 'I-reset',
    languageOptionCebuano: 'Cebuano',
    languageOptionEnglish: 'English',
    languageOptionFilipino: 'Filipino',
    weekdayMonday: 'Lunes',
    weekdayTuesday: 'Martes',
    weekdayWednesday: 'Miyerkules',
    weekdayThursday: 'Huwebes',
    weekdayFriday: 'Biyernes',
    weekdaySaturday: 'Sabado',
    weekdaySunday: 'Domingo',
    providerSettingsPageTitle: 'Settings sa Service Provider',
    providerSettingsPageSubtitle: 'Dumalahon ang imong negosyo ug account preferences',
    providerSettingsNavBusiness: 'Negosyo',
    providerSettingsNavAvailability: 'Availability',
    providerSettingsNavProfileDetails: 'Detalye sa Profile',
    providerSettingsNavPrivacy: 'Privacy',
    providerAccountSettingsTitle: 'Settings sa Account',
    providerPlaceholderFullName: 'Imong tibuok ngalan',
    providerPlaceholderEmail: 'imong.email@example.com',
    providerEmailHelpText: 'Ang imong email gamiton para sa login ug service notifications',
    providerPersonalPhoneLabel: 'Personal nga Numero sa Telepono',
    providerPlaceholderPhone: '+63 912 345 6789',
    providerPasswordSecurityTitle: 'Password ug Security',
    providerChangePassword: 'Usba ang Password',
    providerPasswordSecurityHelp: 'Panalipdi ang imong account pinaagi sa lig-on ug talagsaon nga password',
    providerBusinessInformationTitle: 'Impormasyon sa Negosyo',
    providerBusinessNameLabel: 'Ngalan sa Negosyo',
    providerPlaceholderBusinessName: 'Ngalan sa imong negosyo',
    providerBusinessPhoneLabel: 'Numero sa Telepono sa Negosyo',
    providerBusinessAddressLabel: 'Address sa Negosyo',
    providerPlaceholderBusinessAddress: '123 Business Street',
    providerBusinessCityLabel: 'Syudad sa Negosyo',
    providerPlaceholderBusinessCity: 'Toledo',
    providerMinimumJobAmountLabel: 'Minimum nga Bayad sa Trabaho (P)',
    providerPlaceholderMinimumAmount: '500',
    providerMinimumJobAmountHelp: 'Biyai nga blanko kung walay minimum. Makapadala gihapon og request ang kliyente, pero pwede nimo i-decline.',
    providerServiceAreaLabel: 'Service Area',
    providerServiceAreaToledoCity: 'Toledo City',
    providerServiceAreaToledoPlusBarangays: 'Toledo City + Barangays',
    providerServiceAreaExtended: 'Extended Area (30km)',
    providerServiceAreaProvinceWide: 'Tibuok Probinsya',
    providerAvailabilityJobSettingsTitle: 'Availability ug Job Settings',
    providerSettingsScheduleTitle: 'Schedule ug Booking Settings',
    providerSettingsProfileDetailsTitle: 'Detalye sa Profile',
    providerAvailabilityStatusLabel: 'Status sa Availability',
    providerAvailabilityStatusHelp: 'Ipahibalo sa mga kliyente kung modawat ka karon og trabaho',
    providerAvailabilityStatusAvailable: 'Available',
    providerAvailabilityStatusBusy: 'Busy (Limitado)',
    providerAvailabilityStatusUnavailable: 'Dili Available',
    providerShowAvailabilityStatusLabel: 'Ipakita ang Status sa Availability',
    providerShowAvailabilityStatusHelp: 'Ipakita ang imong availability sa profile',
    providerAutoAcceptRequestsLabel: 'Auto-Dawat sa Service Requests',
    providerAutoAcceptRequestsHelp: 'Awtomatikong dawaton ang requests gikan sa verified clients',
    providerBookingConfigurationTitle: 'Booking Configuration',
    providerAllowSameDayBookingLabel: 'Tugoti ang same-day booking',
    providerMinAdvanceNoticeLabel: 'Pinakagamay nga advance notice (minuto)',
    providerMaxAdvanceBookingDaysLabel: 'Pinakadaghan nga advance booking days',
    providerWeeklyAvailabilityBlocksTitle: 'Semanal nga Availability Blocks',
    providerAddDayBlock: 'Idugang {day}',
    providerNoWeeklyAvailabilityBlocks: 'Wala pay semanal nga availability blocks.',
    providerDayLabel: 'Adlaw',
    requestsEndTime: 'Oras sa pagtapos',
    providerRemoveBlock: 'Tangtanga ang Block',
    providerSaveAvailability: 'I-save ang Availability',
    providerDateExceptionsTitle: 'Date Exceptions',
    providerExceptionDateLabel: 'Petsa sa exception',
    providerExceptionTypeLabel: 'Tipo sa exception',
    providerExceptionTypeAvailableOverride: 'Available override',
    providerExceptionTypeUnavailable: 'Unavailable',
    providerExceptionTypeBooked: 'Booked',
    providerExceptionTypeVacation: 'Vacation',
    providerExceptionStartTimeOptional: 'Oras sa pagsugod (opsyonal)',
    providerExceptionEndTimeOptional: 'Oras sa pagtapos (opsyonal)',
    providerExceptionReasonOptional: 'Rason (opsyonal)',
    providerAddException: 'Idugang ang Exception',
    providerNoDateExceptionsConfigured: 'Walay date exceptions nga na-configure.',
    providerWholeDay: 'Tibuok adlaw',
    providerRemoveException: 'Tangtanga',
    providerSaveLanguages: 'I-save ang mga Pinulongan',
    providerCredentialsCertificatesTitle: 'Credentials ug Certificates',
    providerCredentialNameLabel: 'Ngalan sa credential',
    providerCredentialTypeLabel: 'Tipo sa credential',
    providerIssuingOrganizationLabel: 'Nag-isyu nga organisasyon',
    providerCredentialIdLabel: 'Credential ID',
    providerIssueDateLabel: 'Petsa sa pag-isyu',
    providerExpirationDateLabel: 'Petsa sa expiration',
    providerCredentialDoesNotExpire: 'Kini nga credential dili mo-expire',
    providerCredentialUrlLabel: 'Credential URL',
    providerCredentialDocumentLabel: 'Dokumento (PDF/JPG/PNG)',
    providerAddCredential: 'Idugang ang Credential',
    providerSavedCredentialsTitle: 'Nasave nga Credentials',
    providerLoadingCredentials: 'Nag-load sa credentials...',
    providerNoCredentialsYet: 'Wala pay credentials.',
    providerPendingReview: 'Pending Review',
    providerSubmitForReview: 'Isumite para sa Review',
    providerNotificationSettingsTitle: 'Settings sa Notification',
    providerPushNotificationsLabel: 'Push Notifications',
    providerPushNotificationsHelp: 'Dawata ang browser notifications para sa bag-ong service requests',
    providerEmailAlertsLabel: 'Email Alerts',
    providerEmailAlertsHelp: 'Ma-notify ka sa bag-ong requests ug messages pinaagi sa email',
    providerSmsNotificationsLabel: 'SMS Notifications',
    providerSmsNotificationsHelp: 'Dawata ang importanteng alerts pinaagi sa SMS (posibleng naay bayad)',
    providerPrivacySettingsTitle: 'Settings sa Privacy',
    providerProfileVisibilityLabel: 'Visibility sa Profile',
    providerProfileVisibilityHelp: 'Kinsa ang makakita sa imong profile ug serbisyo',
    providerVisibilityPublic: 'Public',
    providerVisibilityPrivate: 'Private (By Appointment)',
    providerVisibilityVerifiedOnly: 'Verified Clients Only',
    providerAllowDirectMessagesLabel: 'Tugoti ang Direct Messages',
    providerAllowDirectMessagesHelp: 'Tugoti ang mga kliyente nga magpadala nimo og direct message',
    providerSettingsSavedSuccess: 'Nakaluwas ang settings!',
    providerSettingsSaveFailed: 'Napakyas ang pag-save sa settings',
    providerAvailabilityUpdatedSuccess: 'Naka-update ang availability.',
    providerAvailabilitySaveFailed: 'Napakyas ang pag-save sa availability settings',
    providerLanguagesUpdatedSuccess: 'Naka-update ang mga pinulongan.',
    providerLanguagesUpdateFailed: 'Napakyas ang pag-update sa mga pinulongan',
    providerExceptionDateRequired: 'Palihog pili og petsa sa exception.',
    providerExceptionTimePairRequired: 'Ihatag ang start ug end time, o biya-i nga blanko ang duha para whole-day exception.',
    providerAddExceptionFailed: 'Napakyas ang pagdugang sa availability exception',
    providerDeleteExceptionFailed: 'Napakyas ang pagtangtang sa exception',
    providerCredentialNameTypeRequired: 'Kinahanglan ang ngalan ug tipo sa credential.',
    providerCredentialSavedSuccess: 'Nasave ang credential. Isumite kini para sa review kung andam na.',
    providerCredentialCreateFailed: 'Napakyas ang paghimo sa credential',
    providerCredentialSubmittedSuccess: 'Naisumite ang credential para sa review.',
    providerCredentialSubmitFailed: 'Napakyas ang pagsumite sa credential',
    adminReportsLoadError: 'Dili ma-load ang reports. Palihog sulayi pag-usab.',
    adminReportsResolutionNotesRequiredPrompt: 'Resolution notes (kinahanglan):',
    adminReportsResolutionNotesRequiredAlert: 'Kinahanglan ang resolution notes para niini nga aksyon.',
    adminReportsResolutionNotesRequiredMessage: 'Kinahanglan ang resolution notes.',
    adminReportsOptionalModerationNotesPrompt: 'Opsyonal nga moderation notes:',
    adminReportsUpdateFailed: 'Napakyas ang pag-update sa report',
    adminReportsDecisionNoteRequired: 'Kinahanglan ang admin note sa dili pa isumite ang desisyon.',
    adminReportsSubmitDecisionFailed: 'Napakyas ang pagsumite sa desisyon',
    adminReportsSubtitle: 'Susiha ang gi-report nga kalihokan ug pilia ang angay nga aksyon.',
    adminUnderReview: 'Under Review',
    adminProcessed: 'Na-proseso',
    adminSearchReportsPlaceholder: 'Pangita reports...',
    adminFilterReportsByStatus: 'I-filter ang reports pinaagi sa status',
    adminDismissed: 'Dismissed',
    adminResolved: 'Resolved',
    adminActionTaken: 'Aksyon nga gihimo',
    adminEvidenceImage: 'Ebidensya nga hulagway',
    adminViewAttachedEvidenceImage: 'Tan-awa ang naka-attach nga ebidensya nga hulagway',
    adminResolution: 'Resolusyon',
    adminWorking: 'Naga-trabaho...',
    adminReviewReport: 'Susiha ang Report',
    adminMakeDecision: 'Paghimo og Desisyon',
    adminHideDetails: 'Itago ang Detalye',
    adminEvidenceImagePreview: 'Preview sa ebidensya nga hulagway',
    adminCloseImagePreview: 'Sirad-i ang image preview',
    adminNoReportsRequiringAttention: 'Walay reports nga nagkinahanglan og aksyon.',
    adminTryAdjustingSearchFilter: 'Sulayi usba ang imong search o filter criteria.',
    adminCloseDecisionDialog: 'Sirad-i ang decision dialog',
    adminDecision: 'Desisyon',
    adminDecisionDismiss: 'Walay paglapas - Dismiss',
    adminDecisionWarn: 'Gamay nga paglapas - Warn',
    adminDecisionSuspend: 'Seryoso o balik-balik nga paglapas - Suspend',
    adminDecisionBan: 'Grabeng paglapas - Ban',
    adminNote: 'Admin note',
    adminDecisionReasonPlaceholder: 'Isaysay ang rason sa niini nga desisyon',
    adminSubmitting: 'Nagsumite...',
    adminSubmitDecision: 'Isumite ang Desisyon',
    adminOperationalDataRefreshed: 'Na-refresh ang operational data.',
    adminOperationalDataPartialError: 'Adunay operational data nga wala ma-load. Susiha ang API health ug sulayi pag-refresh pag-usab.',
    adminOperationalSnapshotExported: 'Na-export ang operational snapshot.',
    adminSettingsSubtitle: 'Live operations, moderation status, ug admin control shortcuts.',
    adminOverview: 'Overview',
    adminModeration: 'Moderation',
    adminSecurityHealth: 'Security ug Health',
    adminPlatformOperationsOverview: 'Platform Operations Overview',
    adminRefreshing: 'Nag-refresh...',
    adminRefreshMetrics: 'I-refresh ang Metrics',
    adminExportSnapshotJson: 'I-export ang Snapshot JSON',
    adminLiveTotals: 'Live Totals',
    adminSuspendedUsers: 'Suspended users',
    adminUnverifiedProviders: 'Unverified providers',
    adminModerationQueues: 'Moderation Queues',
    adminVerificationRequestsPending: 'Pending nga verification requests',
    adminRejectedVerificationRequests: 'Rejected nga verification requests',
    adminReportsPending: 'Pending nga reports',
    adminReportsUnderReview: 'Reports under review',
    adminModerationActions: 'Moderation Actions',
    adminModerationActionsHelp: 'Ablihi ang dedicated admin pages aron maproseso ang requests ug ma-implementar ang account actions.',
    adminOpenVerificationQueue: 'Ablihi ang Verification Queue',
    adminOpenReportsQueue: 'Ablihi ang Reports Queue',
    adminOpenUserManagement: 'Ablihi ang User Management',
    adminSecurityHealthStatus: 'Status sa Security ug Health',
    adminApiHealth: 'API Health',
    adminTimestamp: 'Timestamp',
    adminNotAvailable: 'Dili available',
    adminEndpoint: 'Endpoint',
    adminDatabase: 'Database',
    adminOperationalNotes: 'Operational Notes',
    adminOperationalNotesLine1: 'Ang Admin Settings gituyo nga read-focused sa kini nga release aron malikayan ang peke nga system toggles.',
    adminOperationalNotesLine2: 'Gamita ang dedicated moderation screens para sa user suspension, provider verification review, ug report handling.',
    adminUserDetailsOverview: 'Overview sa Detalye sa User',
    adminType: 'Type',
    adminNotAvailableShort: 'N/A',
    adminYes: 'Oo',
    adminNo: 'Dili',
    adminUserActivitySummary: 'Summary sa Activity sa User',
    adminTotalRequests: 'Total Requests',
    adminCompletedRequests: 'Completed Requests',
    adminActiveRequests: 'Active Requests',
    adminReportsSubmitted: 'Reports Submitted',
    adminReportsReceived: 'Reports Received',
    adminLastRequestActivity: 'Last Request Activity',
    adminLastReportActivity: 'Last Report Activity',
    adminUsersListMobileAria: 'Listahan sa users para sa mobile',
    adminVerification: 'Verification',
    adminJoinDate: 'Join Date',
    adminUser: 'User',
    adminActions: 'Actions',
    adminCloseDialog: 'Sirad-i ang dialog',
    adminOkay: 'Sige',
    adminRejectionReason: 'Rason sa Rejection',
    adminPreviewGovernmentIdDocument: 'I-preview ang government ID document',
    adminViewGovernmentId: 'Tan-awa ang Government ID',
    adminPreviewCertificationsDocument: 'I-preview ang certifications document',
    adminViewCertifications: 'Tan-awa ang Certifications',
    adminNoDocumentSubmitted: 'Walay dokumento nga naisumite',
    adminApproving: 'Gina-aprubahan...',
    adminApproveVerification: 'Aprubahan ang Verification',
    adminRejectVerification: 'I-reject ang Verification',
    adminPreviewVerificationDocument: 'I-preview ang verification document',
    adminProviderCredentialReviews: 'Provider Credential Reviews',
    adminReviewSubmittedCredentials: 'Susiha ang naisumite nga credentials gikan sa service providers',
    adminExpired: 'Expired',
    adminUnverified: 'Unverified',
    adminLoadingProviderCredentials: 'Nag-load sa provider credentials...',
    adminUnknownProvider: 'Unknown Provider',
    adminCredentialLabel: 'Credential',
    adminCredentialField: 'Credential',
    adminUnnamedCredential: 'Walay ngalan nga credential',
    adminIssuerField: 'Issuer',
    adminNotProvided: 'Wala gihatag',
    adminReviewNote: 'Review Note',
    adminPreviewCredentialDocument: 'I-preview ang credential document',
    adminViewCredentialDocument: 'Tan-awa ang Credential Document',
    adminApproveCredential: 'Aprubahan ang Credential',
    adminRejectCredential: 'I-reject ang Credential',
    adminExpiring: 'Gi-expire...',
    adminMarkExpired: 'Markahi nga Expired',
    adminNoProviderCredentialsFound: 'Walay provider credentials nga nakita',
    adminCloseDocumentPreview: 'Sirad-i ang document preview',
    adminResetImageZoom: 'I-reset ang image zoom',
    adminEnlargeImage: 'Padak-a ang image',
    adminResetZoom: 'I-reset ang Zoom',
    adminEnlarge: 'Padak-a',
    adminPdfPreviewFallback: 'Kung dili ma-preview ang PDF sa browser, basin kinahanglan og download support sa imong environment.',
    adminPreviewUnavailableForType: 'Dili available ang preview para niini nga tipo sa dokumento.',
    adminRejectVerificationRequest: 'I-reject ang Verification Request',
    adminCloseRejectionDialog: 'Sirad-i ang rejection dialog',
    adminConfirmRejection: 'Kumpirmahi ang Rejection',
    adminCloseCredentialRejectionDialog: 'Sirad-i ang credential rejection dialog',
    pendingVerifications: 'Pending Verifications',
    activeReports: 'Active Reports',
    verifiedProviders: 'Verified Providers',
    totalUsers: 'Total Users',
    verificationRequests: 'Verification Requests',
    userReports: 'User Reports',
    loadingVerificationRequests: 'Nag-load sa verification requests...',
    noVerificationRequestsFound: 'Walay verification requests nga nakita',
    noVerificationRequestsInDatabase: 'Wala pay verification requests sa database karon.',
    emailLabel: 'Email',
    submittedLabel: 'Submitted',
    statusLabel: 'Status',
    phoneLabel: 'Phone',
    reviewRequest: 'Susiha ang Request',
    loadingReports: 'Nag-load sa reports...',
    noReportsFound: 'Walay reports nga nakita',
    noReportsInDatabase: 'Wala pay user reports sa database karon.',
    reportedBy: 'Gi-report ni',
    reason: 'Rason',
    date: 'Petsa',
    viewReport: 'Tan-awa ang Report',
    viewAllVerifications: 'Tan-awa ang Tanang Verification ->',
    viewAllReports: 'Tan-awa ang Tanang Report ->',
    failedLoadUsers: 'Napakyas ang pag-load sa users',
    unableLoadDetails: 'Dili ma-load ang detalye',
    failedFetchUserDetails: 'Napakyas ang pagkuha sa user details',
    updateFailed: 'Napakyas ang update',
    failedUpdateUserStatus: 'Napakyas ang pag-update sa user status',
    failedUpdateVerificationStatus: 'Napakyas ang pag-update sa verification status',
    unableLoadActivity: 'Dili ma-load ang activity',
    failedFetchUserActivity: 'Napakyas ang pagkuha sa user activity',
    userManagement: 'User Management',
    userManagementSubtitle: 'Susiha ang status sa account, verification, ug user activity.',
    searchUsersPlaceholder: 'Pangita users...',
    filterUsersByRole: 'I-filter ang users pinaagi sa role',
    allTypes: 'Tanang Type',
    clients: 'Mga Kliyente',
    serviceProviders: 'Mga Service Provider',
    admins: 'Mga Admin',
    filterUsersByStatus: 'I-filter ang users pinaagi sa status sa account',
    allStatuses: 'Tanang Status',
    pending: 'Pending',
    suspended: 'Suspended',
    updating: 'Nag-update...',
    deactivate: 'I-deactivate',
    reactivate: 'I-reactivate',
    unverifyProvider: 'Tangtanga ang Verify sa Provider',
    verifyProvider: 'I-verify ang Provider',
    viewActivity: 'Tan-awa ang Activity',
    loadingUsers: 'Nag-load sa users...',
    failedLoadVerificationRequests: 'Napakyas ang pag-load sa verification requests',
    failedLoadProviderCredentials: 'Napakyas ang pag-load sa provider credentials',
    rejectionReasonRequired: 'Kinahanglan ang rason sa rejection.',
    failedRejectRequest: 'Napakyas ang pag-reject sa request',
    failedReviewRequest: 'Napakyas ang pag-review sa request',
    failedRejectCredential: 'Napakyas ang pag-reject sa credential',
    failedReviewCredential: 'Napakyas ang pag-review sa credential',
    verificationRequestsSubtitle: 'Susiha ug dumalahon ang verification requests sa service provider',
    approved: 'Approved',
    rejected: 'Rejected',
    searchVerificationPlaceholder: 'Pangita pinaagi sa ngalan, email, o propesyon...',
  },
};

const LanguageContext = createContext(null);

const getStorage = () => {
  if (typeof window === 'undefined') {
    return null;
  }

  const storage = window.localStorage;
  if (!storage || typeof storage.getItem !== 'function' || typeof storage.setItem !== 'function') {
    return null;
  }

  return storage;
};

const getInitialLanguage = () => {
  const storage = getStorage();
  const stored = storage?.getItem(STORAGE_KEY);
  if (stored && DICTIONARY[stored]) {
    return stored;
  }

  return DEFAULT_LANGUAGE;
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  const value = useMemo(() => ({
    language,
    setLanguage: (next) => {
      const resolved = DICTIONARY[next] ? next : DEFAULT_LANGUAGE;
      setLanguage(resolved);
      getStorage()?.setItem(STORAGE_KEY, resolved);
    },
    t: (key, vars = null) => {
      const template = DICTIONARY[language]?.[key] || DICTIONARY[DEFAULT_LANGUAGE][key] || key;
      if (!vars || typeof template !== 'string') {
        return template;
      }

      return Object.entries(vars).reduce((result, [name, value]) => {
        return result.replaceAll(`{${name}}`, String(value));
      }, template);
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }

  return context;
}
